
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500

DEFAULT_PAGE = 1
DEFAULT_LIMIT = 10
MAX_LIMIT = 250

DEFAULT_TIMEOUT = 30

VALID_MOVIE_ID = 1
INVALID_MOVIE_ID = 999999999
SEARCH_QUERY_MATRIX = "Матрица"
SEARCH_QUERY_EMPTY = ""

MOVIE_REQUIRED_FIELDS = ["id"]
PERSON_REQUIRED_FIELDS = ["id"]
PAGINATION_FIELDS = ["docs", "total", "limit", "page", "pages"]
